apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: trainbot
  namespace: flux-system
spec:
  image: europe-west2-docker.pkg.dev/slack-api-392013/trainbot-repo/trainbot
  interval: 1m0s
  provider: gcp
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: trainbot
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: trainbot
  filterTags:
    pattern: '^prod-(?P<number>\d+)$'
    extract: '$number'
  policy:
    numerical:
      order: asc
